name: Create Extension Tag
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Tag
        required: true
      git-ref:
        description: Git commit (default HEAD)
        required: false
jobs:
  bump-version:
    name: Creating tag
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: creating tag (Custom Ref)
        run: sh .github/scripts/create-tag.sh -t ${{ github.event.inputs.version }}
        shell: /usr/bin/zsh{0}
